apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: orders-api
  description: Python app that displays time - named orders-api
  annotations:
    github.com/project-slug: whiiplash-platform-lab/orders-api
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=orders-api'
    backstage.io/kubernetes-namespace: dev
spec:
  type: service
  owner: development
  lifecycle: experimental